[package]
name = "v8unpack"
description = "Unpack, pack, deflate and inflate 1C v8 file (*.cf)"
version = "0.1.1"
authors = ["Andreev Alexander <andreevlex.as@gmail.com>"]
homepage = "https://github.com/andreevlex/v8unpack-rs"
repository = "https://github.com/andreevlex/v8unpack-rs"
keywords = ["parser", "binary", "1cd"]
readme = "README.md"
license = "MIT"

[dependencies]
clap = "2.28.0"
v8unpack4rs = "0.1"